-- CreateTable
CREATE TABLE `userdata_tb` (
    `username` VARCHAR(72) NULL,
    `password` VARCHAR(100) NOT NULL,
    `role_id` VARCHAR(36) NOT NULL,
    `role_name` VARCHAR(36) NULL,
    `firstname` VARCHAR(60) NOT NULL,
    `lastname` VARCHAR(60) NULL,
    `business_name` VARCHAR(191) NULL,
    `dob` DATETIME(0) NULL,
    `confirm_pin` VARCHAR(8) NULL,
    `email` VARCHAR(100) NOT NULL,
    `mobile_phone` VARCHAR(20) NULL DEFAULT '000 000 0000',
    `address` VARCHAR(191) NULL,
    `passchg_logon` CHAR(1) NULL,
    `pass_expire` VARCHAR(1) NULL DEFAULT '',
    `pass_dateexpire` DATETIME(0) NULL,
    `pass_change` CHAR(1) NULL,
    `user_disabled` CHAR(1) NULL DEFAULT '0',
    `user_locked` CHAR(1) NULL DEFAULT '0',
    `last_seen` VARCHAR(32) NULL,
    `day_1` CHAR(1) NULL DEFAULT '1',
    `ID_Image_url` CHAR(1) NULL DEFAULT '1',
    `id_number` CHAR(1) NULL DEFAULT '1',
    `org_name` VARCHAR(128) NULL,
    `means_of_ID` CHAR(1) NULL DEFAULT '1',
    `city` CHAR(1) NULL DEFAULT '1',
    `state` CHAR(1) NULL DEFAULT '1',
    `nationality` CHAR(1) NULL DEFAULT '1',
    `pin_missed` INTEGER NULL DEFAULT 0,
    `last_used` DATETIME(0) NULL,
    `modified` DATETIME(0) NULL,
    `hint_question` VARCHAR(100) NULL,
    `hint_answer` VARCHAR(100) NULL,
    `override_wh` CHAR(1) NULL,
    `extend_wh` VARCHAR(17) NULL,
    `created` DATETIME(0) NULL,
    `posted_user` VARCHAR(100) NULL,
    `last_used_passwords` VARCHAR(250) NULL,
    `confirm_code` VARCHAR(128) NULL,
    `confirm_account` VARCHAR(1) NULL DEFAULT '0',
    `business_status` VARCHAR(191) NOT NULL DEFAULT 'NotVerified',
    `user_id` VARCHAR(128) NOT NULL,
    `passport` VARCHAR(255) NULL,
    `referral_code` VARCHAR(16) NULL,
    `status` INTEGER NULL DEFAULT 1,
    `merchantId` CHAR(36) NOT NULL,
    `waddress` VARCHAR(128) NULL DEFAULT '',
    `app` VARCHAR(16) NULL,
    `email_auth` INTEGER NULL DEFAULT 0,
    `resetpassword` VARCHAR(128) NULL,
    `resettime` DATETIME(0) NULL,
    `team_id` CHAR(36) NULL,
    `country` VARCHAR(36) NULL DEFAULT '',
    `last_activity` DATETIME(0) NULL,
    `otp_enabled` VARCHAR(1) NULL DEFAULT '0',
    `otp_verified` VARCHAR(12) NULL,
    `otp_ascii` VARCHAR(128) NULL,
    `otp_hex` VARCHAR(128) NULL,
    `otp_base32` VARCHAR(128) NULL,
    `otp_auth_url` VARCHAR(256) NULL,
    `profilePic` VARCHAR(191) NULL,
    `pk_live` VARCHAR(72) NULL,
    `sk_live` VARCHAR(72) NULL,
    `pk_test` VARCHAR(36) NULL,
    `sk_test` VARCHAR(36) NULL,
    `isExpired` BOOLEAN NOT NULL DEFAULT false,
    `webhook_url` VARCHAR(191) NULL,
    `secret_key` VARCHAR(191) NULL,
    `blacklist` VARCHAR(191) NULL DEFAULT 'False',

    UNIQUE INDEX `email`(`email`),
    UNIQUE INDEX `user_id`(`user_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `customer` (
    `id` CHAR(36) NOT NULL,
    `user_id` VARCHAR(191) NOT NULL,
    `customer_first_name` VARCHAR(191) NULL,
    `customer_last_name` VARCHAR(191) NULL,
    `customer_email` VARCHAR(191) NOT NULL,
    `customer_mobile_number` VARCHAR(191) NOT NULL,
    `status` VARCHAR(191) NULL DEFAULT 'Active',
    `blacklist` VARCHAR(191) NULL DEFAULT 'False',
    `created` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `customer_customer_email_key`(`customer_email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `transactions_tb` (
    `transaction_id` VARCHAR(128) NOT NULL DEFAULT '0',
    `fiat_id` VARCHAR(36) NULL,
    `source_acct` VARCHAR(100) NULL,
    `destination_acct` VARCHAR(100) NULL,
    `trans_type` VARCHAR(50) NULL,
    `transaction_desc` TEXT NULL,
    `transaction_amount` DECIMAL(50, 2) NULL,
    `response_code` VARCHAR(100) NULL,
    `payment_mode` VARCHAR(50) NULL,
    `initial_balance` DECIMAL(50, 2) NULL,
    `current_balance` DECIMAL(50, 2) NULL,
    `receiver_initial_balance` DECIMAL(50, 4) NULL,
    `receiver_current_balance` DECIMAL(50, 4) NULL,
    `posted_ip` VARCHAR(50) NULL,
    `created` VARCHAR(32) NULL,
    `customer_id` VARCHAR(191) NULL,
    `posted_user` VARCHAR(100) NULL,
    `merchant_category` VARCHAR(4) NULL,
    `settlement_status` INTEGER NULL DEFAULT 0,
    `order_id` VARCHAR(200) NULL,
    `category` VARCHAR(16) NULL,
    `session_id` VARCHAR(200) NULL,
    `xml_data` TEXT NULL,
    `tranx_desc` VARCHAR(200) NULL,
    `debit_flag` INTEGER NULL,
    `debit_flag_date` DATE NULL,
    `reversal_flag` INTEGER NULL,
    `reversal_flag_date` DATE NULL,
    `trans_query_id` VARCHAR(128) NULL,
    `merchant_commission` DECIMAL(50, 2) NULL,
    `chargefee` DECIMAL(50, 2) NULL,
    `net_debit_amount` DECIMAL(50, 2) NULL,
    `card_id` INTEGER NULL,
    `response_message` VARCHAR(100) NULL,
    `charge_currency` VARCHAR(10) NULL,
    `disburse_currency` VARCHAR(10) NULL,
    `exchange_rate` DECIMAL(2, 0) NULL,
    `archived` INTEGER NULL,
    `btc_value_supplied` DECIMAL(50, 20) NULL,
    `btc_response` INTEGER NULL,
    `btc_address` VARCHAR(90) NULL,
    `transaction_hash` VARCHAR(50) NULL,
    `btc_time_exceeded` INTEGER NULL,
    `created_btc` DATETIME(0) NULL,
    `btc_value_received` DECIMAL(50, 15) NULL,
    `btc_value_diff` INTEGER NULL,
    `gateway_response_message` VARCHAR(250) NULL,
    `voucher_fee` DECIMAL(2, 0) NULL,
    `gateway_fee` DECIMAL(2, 0) NULL,
    `client_phone` VARCHAR(50) NULL,
    `payment_gateway` VARCHAR(80) NULL,
    `tokenize` INTEGER NULL,
    `user_id` VARCHAR(64) NOT NULL,
    `dev_id` VARCHAR(64) NULL,
    `month` VARCHAR(12) NULL,
    `recipient_name` VARCHAR(72) NULL,
    `refund` VARCHAR(1) NULL,
    `currency` VARCHAR(191) NULL,
    `wallet_id` VARCHAR(191) NULL,
    `status` VARCHAR(191) NULL,
    `payroll_id` VARCHAR(191) NULL,
    `beneficiary_id` VARCHAR(191) NULL,
    `plan_id` CHAR(36) NULL,
    `transaction_date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `OrderIDIndex`(`order_id`),
    INDEX `transactions_tb_plan_fk`(`plan_id`),
    INDEX `PuI`(`posted_user`),
    INDEX `transactions_tb_fiat_id_idx`(`fiat_id`),
    INDEX `RCI`(`response_code`),
    INDEX `SSi`(`settlement_status`),
    INDEX `cDai`(`created`),
    INDEX `mCI`(`merchant_category`),
    INDEX `typeT`(`trans_type`),
    INDEX `transactions_tb_customer_fk`(`customer_id`),
    INDEX `transactions_tb_user_id_fkey`(`user_id`),
    INDEX `transactions_tb_wallet_id_fkey`(`wallet_id`),
    PRIMARY KEY (`transaction_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `store_tb` (
    `store_id` CHAR(36) NOT NULL,
    `user_id` VARCHAR(191) NOT NULL,
    `store_name` VARCHAR(191) NULL,
    `store_address` VARCHAR(191) NULL,
    `store_phone` VARCHAR(191) NULL,
    `store_email` VARCHAR(191) NULL,
    `store_account` VARCHAR(191) NULL,

    PRIMARY KEY (`store_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `fiat_wallet` (
    `wallet_id` CHAR(36) NOT NULL,
    `user_id` VARCHAR(191) NOT NULL,
    `transaction_id` VARCHAR(191) NULL,
    `currency_id` INTEGER NOT NULL,
    `account_number` VARCHAR(191) NULL,
    `currency` VARCHAR(191) NULL,
    `bank_name` VARCHAR(191) NULL,
    `initial_balance` DECIMAL(18, 4) NULL,
    `current_balance` DECIMAL(18, 4) NULL,
    `created` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `account_status` INTEGER NULL,
    `channel` VARCHAR(16) NULL,
    `channel_id` VARCHAR(72) NULL,
    `full_name` VARCHAR(64) NULL,
    `status` VARCHAR(1) NULL,

    UNIQUE INDEX `fiat_wallet_currency_id_key`(`currency_id`),
    UNIQUE INDEX `fiat_wallet_account_number_key`(`account_number`),
    INDEX `wallet_user_id_fkey`(`user_id`),
    PRIMARY KEY (`wallet_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `currency_tb` (
    `currency_id` INTEGER NOT NULL,
    `code` VARCHAR(10) NULL,
    `name` VARCHAR(225) NULL,
    `country` VARCHAR(225) NULL,
    `country_logo` VARCHAR(225) NOT NULL,
    `currency_symbol` VARCHAR(225) NOT NULL,
    `country_id` VARCHAR(191) NULL,

    UNIQUE INDEX `currency_id`(`currency_id`),
    PRIMARY KEY (`currency_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `fiat_wallet` ADD CONSTRAINT `currency_id` FOREIGN KEY (`currency_id`) REFERENCES `currency_tb`(`currency_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
